// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbrkkixunojjiticvvxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRicmtraXh1bm9qaml0aWN2dnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDM0NDgsImV4cCI6MjA3MjkxOTQ0OH0.YmV8_4J_SHr6JPfc0qxvLppmcNgnkxZpymDyYdW_4aE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});